[build]
  publish = "."  # 정적 사이트 루트 폴더
  functions = "netlify/functions"

  [build.environment]
    GOOGLE_CLIENT_ID = "330202967434-9u0gnm9ud2f3oasfp0npn6br4h93qs8i.apps.googleusercontent.com"
    DROPBOX_CLIENT_ID = "ox2nxs1balk4l4i"
    GOOGLE_CLIENT_SECRET = ""  # Netlify UI에서 환경 변수로 설정
    DROPBOX_CLIENT_SECRET = "" # Netlify UI에서 환경 변수로 설정

[[redirects]]
  from = "/auth/google"
  to = "/.netlify/functions/auth-google"
  status = 200

[[redirects]]
  from = "/auth/google/callback"
  to = "/.netlify/functions/google-callback"
  status = 200

[[redirects]]
  from = "/auth/dropbox"
  to = "/.netlify/functions/auth-dropbox"
  status = 200

[[redirects]]
  from = "/auth/dropbox/callback"
  to = "/.netlify/functions/dropbox-callback"
  status = 200

[[redirects]]
  from = "/upload"
  to = "/.netlify/functions/unified-upload"
  status = 200
