[build]
  publish = "dist"  # 배포 디렉토리 (필요 시 'dist'를 'public' 또는 실제 폴더로 수정)
  functions = "netlify/functions"

  [build.environment]
    GOOGLE_CLIENT_ID = "330202967434-9u0gnm9ud2f3oasfp0npn6br4h93qs8i.apps.googleusercontent.com"
    DROPBOX_CLIENT_ID = "ox2nxs1balk4l4i"
    GOOGLE_CLIENT_SECRET = ""  # Netlify UI에서 설정
    DROPBOX_CLIENT_SECRET = "" # Netlify UI에서 설정

# 자동 리디렉션 설정
[[redirects]]
  from = "/auth/google"
  to = "/.netlify/functions/auth-google"
  status = 200

[[redirects]]
  from = "/auth/google/callback"
  to = "/.netlify/functions/google-callback"
  status = 200

[[redirects]]
  from = "/auth/dropbox"
  to = "/.netlify/functions/auth-dropbox"
  status = 200

[[redirects]]
  from = "/auth/dropbox/callback"
  to = "/.netlify/functions/dropbox-callback"
  status = 200

[[redirects]]
  from = "/upload"
  to = "/.netlify/functions/unified-upload"
  status = 200

# Netlify Plugin 예시 (선택 사항)
[[plugins]]
  package = "@netlify/plugin-lighthouse"
