[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/auth/dropbox"
  to = "/.netlify/functions/auth-dropbox"
  status = 200

[[redirects]]
  from = "/auth/dropbox/callback"
  to = "/.netlify/functions/dropbox-callback"
  status = 200

[[redirects]]
  from = "/auth/google"
  to = "/.netlify/functions/auth-google"
  status = 200

[[redirects]]
  from = "/auth/google/callback"
  to = "/.netlify/functions/google-callback"
  status = 200

[[redirects]]
  from = "/upload"
  to = "/.netlify/functions/unified-upload"
  status = 200
